version: '3.12'
services:
  web:
    container_name: random_names_backend
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
   
    ports:
      - "8081:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5000:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
  